language: "en"
reviews:
  request_changes: false
  guidelines: |
    - Ensure code aligns with /specs/*.md
    - Check for TDD coverage
    - No direct API calls; use MCP
    - Flag security issues (secrets, injection, unsafe deserialization)